import "./globals.css";
import { Providers } from "@/redux/provider";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "kmjang-blog",
  description: "Generated by kmjang",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
