import "./globals.css";
import { Providers } from "@/redux/provider";
import Nav from "./components/Nav";

import type { Metadata } from "next";
import Wrapper from "./components/Wrapper";

export const metadata: Metadata = {
  title: "kmjang-blog",
  description: "Generated by kmjang",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Providers>
        <Wrapper>
          <Nav />
          {children}
        </Wrapper>
      </Providers>
    </html>
  );
}
